# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:7-jdk11-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test


build:
  stage: build
  script:
    - gradle --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - gradle check
  artifacts:
    when: always
    reports:
      junit: ./build/test-results/test/**/TEST-*.xml
    paths:
      - build/reports
      - build/jacoco/*.exec
